// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: Broker/proto/Broker.proto

package Broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_ProcesarEscritura_FullMethodName = "/Broker.BrokerService/ProcesarEscritura"
	BrokerService_ProcesarLectura_FullMethodName   = "/Broker.BrokerService/ProcesarLectura"
	BrokerService_ActualizarPedido_FullMethodName  = "/Broker.BrokerService/ActualizarPedido"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	// Para solicitudes del Gateway (escrituras sin afinidad o con afinidad)
	ProcesarEscritura(ctx context.Context, in *EscrituraBrokerRequest, opts ...grpc.CallOption) (*EscrituraBrokerResponse, error)
	// Para consultas del Gateway (lecturas sin afinidad)
	ProcesarLectura(ctx context.Context, in *LecturaBrokerRequest, opts ...grpc.CallOption) (*LecturaBrokerResponse, error)
	// Para actualizaciones del Productor (eventos logísticos)
	ActualizarPedido(ctx context.Context, in *ActualizacionProductorRequest, opts ...grpc.CallOption) (*ActualizacionProductorResponse, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) ProcesarEscritura(ctx context.Context, in *EscrituraBrokerRequest, opts ...grpc.CallOption) (*EscrituraBrokerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscrituraBrokerResponse)
	err := c.cc.Invoke(ctx, BrokerService_ProcesarEscritura_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) ProcesarLectura(ctx context.Context, in *LecturaBrokerRequest, opts ...grpc.CallOption) (*LecturaBrokerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LecturaBrokerResponse)
	err := c.cc.Invoke(ctx, BrokerService_ProcesarLectura_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) ActualizarPedido(ctx context.Context, in *ActualizacionProductorRequest, opts ...grpc.CallOption) (*ActualizacionProductorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizacionProductorResponse)
	err := c.cc.Invoke(ctx, BrokerService_ActualizarPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
type BrokerServiceServer interface {
	// Para solicitudes del Gateway (escrituras sin afinidad o con afinidad)
	ProcesarEscritura(context.Context, *EscrituraBrokerRequest) (*EscrituraBrokerResponse, error)
	// Para consultas del Gateway (lecturas sin afinidad)
	ProcesarLectura(context.Context, *LecturaBrokerRequest) (*LecturaBrokerResponse, error)
	// Para actualizaciones del Productor (eventos logísticos)
	ActualizarPedido(context.Context, *ActualizacionProductorRequest) (*ActualizacionProductorResponse, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) ProcesarEscritura(context.Context, *EscrituraBrokerRequest) (*EscrituraBrokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcesarEscritura not implemented")
}
func (UnimplementedBrokerServiceServer) ProcesarLectura(context.Context, *LecturaBrokerRequest) (*LecturaBrokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcesarLectura not implemented")
}
func (UnimplementedBrokerServiceServer) ActualizarPedido(context.Context, *ActualizacionProductorRequest) (*ActualizacionProductorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActualizarPedido not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_ProcesarEscritura_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscrituraBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ProcesarEscritura(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_ProcesarEscritura_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ProcesarEscritura(ctx, req.(*EscrituraBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_ProcesarLectura_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LecturaBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ProcesarLectura(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_ProcesarLectura_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ProcesarLectura(ctx, req.(*LecturaBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_ActualizarPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizacionProductorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ActualizarPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_ActualizarPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ActualizarPedido(ctx, req.(*ActualizacionProductorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Broker.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcesarEscritura",
			Handler:    _BrokerService_ProcesarEscritura_Handler,
		},
		{
			MethodName: "ProcesarLectura",
			Handler:    _BrokerService_ProcesarLectura_Handler,
		},
		{
			MethodName: "ActualizarPedido",
			Handler:    _BrokerService_ActualizarPedido_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Broker/proto/Broker.proto",
}
