// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: Broker/proto/Broker.proto

package Broker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EscrituraBrokerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PedidoId       string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado         string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	TargetDatanode string                 `protobuf:"bytes,3,opt,name=target_datanode,json=targetDatanode,proto3" json:"target_datanode,omitempty"` // IP:Port del Datanode seleccionado por el Gateway
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EscrituraBrokerRequest) Reset() {
	*x = EscrituraBrokerRequest{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrituraBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrituraBrokerRequest) ProtoMessage() {}

func (x *EscrituraBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrituraBrokerRequest.ProtoReflect.Descriptor instead.
func (*EscrituraBrokerRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{0}
}

func (x *EscrituraBrokerRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *EscrituraBrokerRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *EscrituraBrokerRequest) GetTargetDatanode() string {
	if x != nil {
		return x.TargetDatanode
	}
	return ""
}

type EscrituraBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrituraBrokerResponse) Reset() {
	*x = EscrituraBrokerResponse{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrituraBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrituraBrokerResponse) ProtoMessage() {}

func (x *EscrituraBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrituraBrokerResponse.ProtoReflect.Descriptor instead.
func (*EscrituraBrokerResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{1}
}

func (x *EscrituraBrokerResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type LecturaBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LecturaBrokerRequest) Reset() {
	*x = LecturaBrokerRequest{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LecturaBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LecturaBrokerRequest) ProtoMessage() {}

func (x *LecturaBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LecturaBrokerRequest.ProtoReflect.Descriptor instead.
func (*LecturaBrokerRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{2}
}

func (x *LecturaBrokerRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type LecturaBrokerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Estado         string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	RelojVectorial []int32                `protobuf:"varint,2,rep,packed,name=RelojVectorial,proto3" json:"RelojVectorial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LecturaBrokerResponse) Reset() {
	*x = LecturaBrokerResponse{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LecturaBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LecturaBrokerResponse) ProtoMessage() {}

func (x *LecturaBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LecturaBrokerResponse.ProtoReflect.Descriptor instead.
func (*LecturaBrokerResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{3}
}

func (x *LecturaBrokerResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *LecturaBrokerResponse) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type ActualizacionProductorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PedidoId       string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado         string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	RelojVectorial []int32                `protobuf:"varint,3,rep,packed,name=RelojVectorial,proto3" json:"RelojVectorial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActualizacionProductorRequest) Reset() {
	*x = ActualizacionProductorRequest{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizacionProductorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionProductorRequest) ProtoMessage() {}

func (x *ActualizacionProductorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionProductorRequest.ProtoReflect.Descriptor instead.
func (*ActualizacionProductorRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{4}
}

func (x *ActualizacionProductorRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *ActualizacionProductorRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ActualizacionProductorRequest) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type ActualizacionProductorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizacionProductorResponse) Reset() {
	*x = ActualizacionProductorResponse{}
	mi := &file_Broker_proto_Broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizacionProductorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionProductorResponse) ProtoMessage() {}

func (x *ActualizacionProductorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_Broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionProductorResponse.ProtoReflect.Descriptor instead.
func (*ActualizacionProductorResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_Broker_proto_rawDescGZIP(), []int{5}
}

func (x *ActualizacionProductorResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

var File_Broker_proto_Broker_proto protoreflect.FileDescriptor

const file_Broker_proto_Broker_proto_rawDesc = "" +
	"\n" +
	"\x19Broker/proto/Broker.proto\x12\x06Broker\"v\n" +
	"\x16EscrituraBrokerRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12'\n" +
	"\x0ftarget_datanode\x18\x03 \x01(\tR\x0etargetDatanode\"/\n" +
	"\x17EscrituraBrokerResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\"3\n" +
	"\x14LecturaBrokerRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\"W\n" +
	"\x15LecturaBrokerResponse\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12&\n" +
	"\x0eRelojVectorial\x18\x02 \x03(\x05R\x0eRelojVectorial\"|\n" +
	"\x1dActualizacionProductorRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12&\n" +
	"\x0eRelojVectorial\x18\x03 \x03(\x05R\x0eRelojVectorial\"6\n" +
	"\x1eActualizacionProductorResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito2\x98\x02\n" +
	"\rBrokerService\x12T\n" +
	"\x11ProcesarEscritura\x12\x1e.Broker.EscrituraBrokerRequest\x1a\x1f.Broker.EscrituraBrokerResponse\x12N\n" +
	"\x0fProcesarLectura\x12\x1c.Broker.LecturaBrokerRequest\x1a\x1d.Broker.LecturaBrokerResponse\x12a\n" +
	"\x10ActualizarPedido\x12%.Broker.ActualizacionProductorRequest\x1a&.Broker.ActualizacionProductorResponseB\n" +
	"Z\b./Brokerb\x06proto3"

var (
	file_Broker_proto_Broker_proto_rawDescOnce sync.Once
	file_Broker_proto_Broker_proto_rawDescData []byte
)

func file_Broker_proto_Broker_proto_rawDescGZIP() []byte {
	file_Broker_proto_Broker_proto_rawDescOnce.Do(func() {
		file_Broker_proto_Broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Broker_proto_Broker_proto_rawDesc), len(file_Broker_proto_Broker_proto_rawDesc)))
	})
	return file_Broker_proto_Broker_proto_rawDescData
}

var file_Broker_proto_Broker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Broker_proto_Broker_proto_goTypes = []any{
	(*EscrituraBrokerRequest)(nil),         // 0: Broker.EscrituraBrokerRequest
	(*EscrituraBrokerResponse)(nil),        // 1: Broker.EscrituraBrokerResponse
	(*LecturaBrokerRequest)(nil),           // 2: Broker.LecturaBrokerRequest
	(*LecturaBrokerResponse)(nil),          // 3: Broker.LecturaBrokerResponse
	(*ActualizacionProductorRequest)(nil),  // 4: Broker.ActualizacionProductorRequest
	(*ActualizacionProductorResponse)(nil), // 5: Broker.ActualizacionProductorResponse
}
var file_Broker_proto_Broker_proto_depIdxs = []int32{
	0, // 0: Broker.BrokerService.ProcesarEscritura:input_type -> Broker.EscrituraBrokerRequest
	2, // 1: Broker.BrokerService.ProcesarLectura:input_type -> Broker.LecturaBrokerRequest
	4, // 2: Broker.BrokerService.ActualizarPedido:input_type -> Broker.ActualizacionProductorRequest
	1, // 3: Broker.BrokerService.ProcesarEscritura:output_type -> Broker.EscrituraBrokerResponse
	3, // 4: Broker.BrokerService.ProcesarLectura:output_type -> Broker.LecturaBrokerResponse
	5, // 5: Broker.BrokerService.ActualizarPedido:output_type -> Broker.ActualizacionProductorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Broker_proto_Broker_proto_init() }
func file_Broker_proto_Broker_proto_init() {
	if File_Broker_proto_Broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Broker_proto_Broker_proto_rawDesc), len(file_Broker_proto_Broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Broker_proto_Broker_proto_goTypes,
		DependencyIndexes: file_Broker_proto_Broker_proto_depIdxs,
		MessageInfos:      file_Broker_proto_Broker_proto_msgTypes,
	}.Build()
	File_Broker_proto_Broker_proto = out.File
	file_Broker_proto_Broker_proto_goTypes = nil
	file_Broker_proto_Broker_proto_depIdxs = nil
}
