// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: Datanode/proto/Datanode.proto

package Datanode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatanodeService_EscribirPedido_FullMethodName    = "/Datanode.DatanodeService/EscribirPedido"
	DatanodeService_ObtenerPedido_FullMethodName     = "/Datanode.DatanodeService/ObtenerPedido"
	DatanodeService_IntercambioGossip_FullMethodName = "/Datanode.DatanodeService/IntercambioGossip"
	DatanodeService_MandarAuditoria_FullMethodName   = "/Datanode.DatanodeService/MandarAuditoria"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	EscribirPedido(ctx context.Context, in *EscribirPedidoRequest, opts ...grpc.CallOption) (*EscribirPedidoResponse, error)
	ObtenerPedido(ctx context.Context, in *ObtenerPedidoRequest, opts ...grpc.CallOption) (*ObtenerPedidoResponse, error)
	IntercambioGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
	MandarAuditoria(ctx context.Context, in *AuditoriaRequest, opts ...grpc.CallOption) (*AuditoriaResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) EscribirPedido(ctx context.Context, in *EscribirPedidoRequest, opts ...grpc.CallOption) (*EscribirPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscribirPedidoResponse)
	err := c.cc.Invoke(ctx, DatanodeService_EscribirPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) ObtenerPedido(ctx context.Context, in *ObtenerPedidoRequest, opts ...grpc.CallOption) (*ObtenerPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerPedidoResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ObtenerPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) IntercambioGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, DatanodeService_IntercambioGossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) MandarAuditoria(ctx context.Context, in *AuditoriaRequest, opts ...grpc.CallOption) (*AuditoriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditoriaResponse)
	err := c.cc.Invoke(ctx, DatanodeService_MandarAuditoria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
type DatanodeServiceServer interface {
	EscribirPedido(context.Context, *EscribirPedidoRequest) (*EscribirPedidoResponse, error)
	ObtenerPedido(context.Context, *ObtenerPedidoRequest) (*ObtenerPedidoResponse, error)
	IntercambioGossip(context.Context, *GossipRequest) (*GossipResponse, error)
	MandarAuditoria(context.Context, *AuditoriaRequest) (*AuditoriaResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) EscribirPedido(context.Context, *EscribirPedidoRequest) (*EscribirPedidoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EscribirPedido not implemented")
}
func (UnimplementedDatanodeServiceServer) ObtenerPedido(context.Context, *ObtenerPedidoRequest) (*ObtenerPedidoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerPedido not implemented")
}
func (UnimplementedDatanodeServiceServer) IntercambioGossip(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntercambioGossip not implemented")
}
func (UnimplementedDatanodeServiceServer) MandarAuditoria(context.Context, *AuditoriaRequest) (*AuditoriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MandarAuditoria not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_EscribirPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscribirPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).EscribirPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_EscribirPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).EscribirPedido(ctx, req.(*EscribirPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_ObtenerPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ObtenerPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ObtenerPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ObtenerPedido(ctx, req.(*ObtenerPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_IntercambioGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).IntercambioGossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_IntercambioGossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).IntercambioGossip(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_MandarAuditoria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditoriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).MandarAuditoria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_MandarAuditoria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).MandarAuditoria(ctx, req.(*AuditoriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Datanode.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EscribirPedido",
			Handler:    _DatanodeService_EscribirPedido_Handler,
		},
		{
			MethodName: "ObtenerPedido",
			Handler:    _DatanodeService_ObtenerPedido_Handler,
		},
		{
			MethodName: "IntercambioGossip",
			Handler:    _DatanodeService_IntercambioGossip_Handler,
		},
		{
			MethodName: "MandarAuditoria",
			Handler:    _DatanodeService_MandarAuditoria_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Datanode/proto/Datanode.proto",
}
