// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: Datanode/proto/Datanode.proto

package Datanode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EscribirPedidoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PedidoId       string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado         string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	RelojVectorial []int32                `protobuf:"varint,3,rep,packed,name=RelojVectorial,proto3" json:"RelojVectorial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EscribirPedidoRequest) Reset() {
	*x = EscribirPedidoRequest{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscribirPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscribirPedidoRequest) ProtoMessage() {}

func (x *EscribirPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscribirPedidoRequest.ProtoReflect.Descriptor instead.
func (*EscribirPedidoRequest) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{0}
}

func (x *EscribirPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *EscribirPedidoRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *EscribirPedidoRequest) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type EscribirPedidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscribirPedidoResponse) Reset() {
	*x = EscribirPedidoResponse{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscribirPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscribirPedidoResponse) ProtoMessage() {}

func (x *EscribirPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscribirPedidoResponse.ProtoReflect.Descriptor instead.
func (*EscribirPedidoResponse) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{1}
}

func (x *EscribirPedidoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type ObtenerPedidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerPedidoRequest) Reset() {
	*x = ObtenerPedidoRequest{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerPedidoRequest) ProtoMessage() {}

func (x *ObtenerPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerPedidoRequest.ProtoReflect.Descriptor instead.
func (*ObtenerPedidoRequest) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{2}
}

func (x *ObtenerPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type ObtenerPedidoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PedidoId       string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado         string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	RelojVectorial []int32                `protobuf:"varint,3,rep,packed,name=RelojVectorial,proto3" json:"RelojVectorial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObtenerPedidoResponse) Reset() {
	*x = ObtenerPedidoResponse{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerPedidoResponse) ProtoMessage() {}

func (x *ObtenerPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerPedidoResponse.ProtoReflect.Descriptor instead.
func (*ObtenerPedidoResponse) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{3}
}

func (x *ObtenerPedidoResponse) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *ObtenerPedidoResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ObtenerPedidoResponse) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type GossipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Estructura para enviar todo el mapa de pedidos locales de un nodo a otro
	CatalogoPedidos map[string]*EscribirPedidoRequest `protobuf:"bytes,1,rep,name=catalogo_pedidos,json=catalogoPedidos,proto3" json:"catalogo_pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{4}
}

func (x *GossipRequest) GetCatalogoPedidos() map[string]*EscribirPedidoRequest {
	if x != nil {
		return x.CatalogoPedidos
	}
	return nil
}

type GossipResponse struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	Ack             bool                              `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	CatalogoPedidos map[string]*EscribirPedidoRequest `protobuf:"bytes,2,rep,name=catalogo_pedidos,json=catalogoPedidos,proto3" json:"catalogo_pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{5}
}

func (x *GossipResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *GossipResponse) GetCatalogoPedidos() map[string]*EscribirPedidoRequest {
	if x != nil {
		return x.CatalogoPedidos
	}
	return nil
}

type AuditoriaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MensajeControl string                 `protobuf:"bytes,1,opt,name=mensaje_control,json=mensajeControl,proto3" json:"mensaje_control,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditoriaRequest) Reset() {
	*x = AuditoriaRequest{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditoriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditoriaRequest) ProtoMessage() {}

func (x *AuditoriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditoriaRequest.ProtoReflect.Descriptor instead.
func (*AuditoriaRequest) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{6}
}

func (x *AuditoriaRequest) GetMensajeControl() string {
	if x != nil {
		return x.MensajeControl
	}
	return ""
}

type AuditoriaResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ArchivoCreado bool                              `protobuf:"varint,1,opt,name=archivo_creado,json=archivoCreado,proto3" json:"archivo_creado,omitempty"`
	Catalogo      map[string]*EscribirPedidoRequest `protobuf:"bytes,2,rep,name=catalogo,proto3" json:"catalogo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditoriaResponse) Reset() {
	*x = AuditoriaResponse{}
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditoriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditoriaResponse) ProtoMessage() {}

func (x *AuditoriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datanode_proto_Datanode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditoriaResponse.ProtoReflect.Descriptor instead.
func (*AuditoriaResponse) Descriptor() ([]byte, []int) {
	return file_Datanode_proto_Datanode_proto_rawDescGZIP(), []int{7}
}

func (x *AuditoriaResponse) GetArchivoCreado() bool {
	if x != nil {
		return x.ArchivoCreado
	}
	return false
}

func (x *AuditoriaResponse) GetCatalogo() map[string]*EscribirPedidoRequest {
	if x != nil {
		return x.Catalogo
	}
	return nil
}

var File_Datanode_proto_Datanode_proto protoreflect.FileDescriptor

const file_Datanode_proto_Datanode_proto_rawDesc = "" +
	"\n" +
	"\x1dDatanode/proto/Datanode.proto\x12\bDatanode\"t\n" +
	"\x15EscribirPedidoRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12&\n" +
	"\x0eRelojVectorial\x18\x03 \x03(\x05R\x0eRelojVectorial\".\n" +
	"\x16EscribirPedidoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\"3\n" +
	"\x14ObtenerPedidoRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\"t\n" +
	"\x15ObtenerPedidoResponse\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12&\n" +
	"\x0eRelojVectorial\x18\x03 \x03(\x05R\x0eRelojVectorial\"\xcd\x01\n" +
	"\rGossipRequest\x12W\n" +
	"\x10catalogo_pedidos\x18\x01 \x03(\v2,.Datanode.GossipRequest.CatalogoPedidosEntryR\x0fcatalogoPedidos\x1ac\n" +
	"\x14CatalogoPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.Datanode.EscribirPedidoRequestR\x05value:\x028\x01\"\xe1\x01\n" +
	"\x0eGossipResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12X\n" +
	"\x10catalogo_pedidos\x18\x02 \x03(\v2-.Datanode.GossipResponse.CatalogoPedidosEntryR\x0fcatalogoPedidos\x1ac\n" +
	"\x14CatalogoPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.Datanode.EscribirPedidoRequestR\x05value:\x028\x01\";\n" +
	"\x10AuditoriaRequest\x12'\n" +
	"\x0fmensaje_control\x18\x01 \x01(\tR\x0emensajeControl\"\xdf\x01\n" +
	"\x11AuditoriaResponse\x12%\n" +
	"\x0earchivo_creado\x18\x01 \x01(\bR\rarchivoCreado\x12E\n" +
	"\bcatalogo\x18\x02 \x03(\v2).Datanode.AuditoriaResponse.CatalogoEntryR\bcatalogo\x1a\\\n" +
	"\rCatalogoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.Datanode.EscribirPedidoRequestR\x05value:\x028\x012\xcc\x02\n" +
	"\x0fDatanodeService\x12S\n" +
	"\x0eEscribirPedido\x12\x1f.Datanode.EscribirPedidoRequest\x1a .Datanode.EscribirPedidoResponse\x12P\n" +
	"\rObtenerPedido\x12\x1e.Datanode.ObtenerPedidoRequest\x1a\x1f.Datanode.ObtenerPedidoResponse\x12F\n" +
	"\x11IntercambioGossip\x12\x17.Datanode.GossipRequest\x1a\x18.Datanode.GossipResponse\x12J\n" +
	"\x0fMandarAuditoria\x12\x1a.Datanode.AuditoriaRequest\x1a\x1b.Datanode.AuditoriaResponseB\fZ\n" +
	"./Datanodeb\x06proto3"

var (
	file_Datanode_proto_Datanode_proto_rawDescOnce sync.Once
	file_Datanode_proto_Datanode_proto_rawDescData []byte
)

func file_Datanode_proto_Datanode_proto_rawDescGZIP() []byte {
	file_Datanode_proto_Datanode_proto_rawDescOnce.Do(func() {
		file_Datanode_proto_Datanode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Datanode_proto_Datanode_proto_rawDesc), len(file_Datanode_proto_Datanode_proto_rawDesc)))
	})
	return file_Datanode_proto_Datanode_proto_rawDescData
}

var file_Datanode_proto_Datanode_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Datanode_proto_Datanode_proto_goTypes = []any{
	(*EscribirPedidoRequest)(nil),  // 0: Datanode.EscribirPedidoRequest
	(*EscribirPedidoResponse)(nil), // 1: Datanode.EscribirPedidoResponse
	(*ObtenerPedidoRequest)(nil),   // 2: Datanode.ObtenerPedidoRequest
	(*ObtenerPedidoResponse)(nil),  // 3: Datanode.ObtenerPedidoResponse
	(*GossipRequest)(nil),          // 4: Datanode.GossipRequest
	(*GossipResponse)(nil),         // 5: Datanode.GossipResponse
	(*AuditoriaRequest)(nil),       // 6: Datanode.AuditoriaRequest
	(*AuditoriaResponse)(nil),      // 7: Datanode.AuditoriaResponse
	nil,                            // 8: Datanode.GossipRequest.CatalogoPedidosEntry
	nil,                            // 9: Datanode.GossipResponse.CatalogoPedidosEntry
	nil,                            // 10: Datanode.AuditoriaResponse.CatalogoEntry
}
var file_Datanode_proto_Datanode_proto_depIdxs = []int32{
	8,  // 0: Datanode.GossipRequest.catalogo_pedidos:type_name -> Datanode.GossipRequest.CatalogoPedidosEntry
	9,  // 1: Datanode.GossipResponse.catalogo_pedidos:type_name -> Datanode.GossipResponse.CatalogoPedidosEntry
	10, // 2: Datanode.AuditoriaResponse.catalogo:type_name -> Datanode.AuditoriaResponse.CatalogoEntry
	0,  // 3: Datanode.GossipRequest.CatalogoPedidosEntry.value:type_name -> Datanode.EscribirPedidoRequest
	0,  // 4: Datanode.GossipResponse.CatalogoPedidosEntry.value:type_name -> Datanode.EscribirPedidoRequest
	0,  // 5: Datanode.AuditoriaResponse.CatalogoEntry.value:type_name -> Datanode.EscribirPedidoRequest
	0,  // 6: Datanode.DatanodeService.EscribirPedido:input_type -> Datanode.EscribirPedidoRequest
	2,  // 7: Datanode.DatanodeService.ObtenerPedido:input_type -> Datanode.ObtenerPedidoRequest
	4,  // 8: Datanode.DatanodeService.IntercambioGossip:input_type -> Datanode.GossipRequest
	6,  // 9: Datanode.DatanodeService.MandarAuditoria:input_type -> Datanode.AuditoriaRequest
	1,  // 10: Datanode.DatanodeService.EscribirPedido:output_type -> Datanode.EscribirPedidoResponse
	3,  // 11: Datanode.DatanodeService.ObtenerPedido:output_type -> Datanode.ObtenerPedidoResponse
	5,  // 12: Datanode.DatanodeService.IntercambioGossip:output_type -> Datanode.GossipResponse
	7,  // 13: Datanode.DatanodeService.MandarAuditoria:output_type -> Datanode.AuditoriaResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Datanode_proto_Datanode_proto_init() }
func file_Datanode_proto_Datanode_proto_init() {
	if File_Datanode_proto_Datanode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Datanode_proto_Datanode_proto_rawDesc), len(file_Datanode_proto_Datanode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Datanode_proto_Datanode_proto_goTypes,
		DependencyIndexes: file_Datanode_proto_Datanode_proto_depIdxs,
		MessageInfos:      file_Datanode_proto_Datanode_proto_msgTypes,
	}.Build()
	File_Datanode_proto_Datanode_proto = out.File
	file_Datanode_proto_Datanode_proto_goTypes = nil
	file_Datanode_proto_Datanode_proto_depIdxs = nil
}
