// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: Gateway/proto/Gateway.proto

package Gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrearPedidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoRequest) Reset() {
	*x = CrearPedidoRequest{}
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoRequest) ProtoMessage() {}

func (x *CrearPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoRequest.ProtoReflect.Descriptor instead.
func (*CrearPedidoRequest) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_Gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CrearPedidoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CrearPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type CrearPedidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoResponse) Reset() {
	*x = CrearPedidoResponse{}
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoResponse) ProtoMessage() {}

func (x *CrearPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoResponse.ProtoReflect.Descriptor instead.
func (*CrearPedidoResponse) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_Gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CrearPedidoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearPedidoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_Gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ConsultarEstadoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ConsultarEstadoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type ConsultarEstadoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Estado         string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	RelojVectorial []int32                `protobuf:"varint,2,rep,packed,name=RelojVectorial,proto3" json:"RelojVectorial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_Gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_Gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultarEstadoResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ConsultarEstadoResponse) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

var File_Gateway_proto_Gateway_proto protoreflect.FileDescriptor

const file_Gateway_proto_Gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bGateway/proto/Gateway.proto\x12\aGateway\"P\n" +
	"\x12CrearPedidoRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\"E\n" +
	"\x13CrearPedidoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"T\n" +
	"\x16ConsultarEstadoRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\"Y\n" +
	"\x17ConsultarEstadoResponse\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12&\n" +
	"\x0eRelojVectorial\x18\x02 \x03(\x05R\x0eRelojVectorial2\xb0\x01\n" +
	"\x0eGatewayService\x12H\n" +
	"\vCrearPedido\x12\x1b.Gateway.CrearPedidoRequest\x1a\x1c.Gateway.CrearPedidoResponse\x12T\n" +
	"\x0fConsultarEstado\x12\x1f.Gateway.ConsultarEstadoRequest\x1a .Gateway.ConsultarEstadoResponseB\vZ\t./Gatewayb\x06proto3"

var (
	file_Gateway_proto_Gateway_proto_rawDescOnce sync.Once
	file_Gateway_proto_Gateway_proto_rawDescData []byte
)

func file_Gateway_proto_Gateway_proto_rawDescGZIP() []byte {
	file_Gateway_proto_Gateway_proto_rawDescOnce.Do(func() {
		file_Gateway_proto_Gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Gateway_proto_Gateway_proto_rawDesc), len(file_Gateway_proto_Gateway_proto_rawDesc)))
	})
	return file_Gateway_proto_Gateway_proto_rawDescData
}

var file_Gateway_proto_Gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Gateway_proto_Gateway_proto_goTypes = []any{
	(*CrearPedidoRequest)(nil),      // 0: Gateway.CrearPedidoRequest
	(*CrearPedidoResponse)(nil),     // 1: Gateway.CrearPedidoResponse
	(*ConsultarEstadoRequest)(nil),  // 2: Gateway.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil), // 3: Gateway.ConsultarEstadoResponse
}
var file_Gateway_proto_Gateway_proto_depIdxs = []int32{
	0, // 0: Gateway.GatewayService.CrearPedido:input_type -> Gateway.CrearPedidoRequest
	2, // 1: Gateway.GatewayService.ConsultarEstado:input_type -> Gateway.ConsultarEstadoRequest
	1, // 2: Gateway.GatewayService.CrearPedido:output_type -> Gateway.CrearPedidoResponse
	3, // 3: Gateway.GatewayService.ConsultarEstado:output_type -> Gateway.ConsultarEstadoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Gateway_proto_Gateway_proto_init() }
func file_Gateway_proto_Gateway_proto_init() {
	if File_Gateway_proto_Gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Gateway_proto_Gateway_proto_rawDesc), len(file_Gateway_proto_Gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Gateway_proto_Gateway_proto_goTypes,
		DependencyIndexes: file_Gateway_proto_Gateway_proto_depIdxs,
		MessageInfos:      file_Gateway_proto_Gateway_proto_msgTypes,
	}.Build()
	File_Gateway_proto_Gateway_proto = out.File
	file_Gateway_proto_Gateway_proto_goTypes = nil
	file_Gateway_proto_Gateway_proto_depIdxs = nil
}
